name: PR build

on:
  workflow_call:
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-distribution: temurin
          java-version: 21
          maven-version: 3.9.9
          cache-enabled: true

      - name: Maven deploy
        run: mvn --batch-mode --update-snapshots verify
